# Generated by Django 2.0.7 on 2018-07-11 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40, verbose_name='Address to')),
                ('amount', models.ImageField(upload_to='', verbose_name='Amount of tokens')),
            ],
            options={
                'verbose_name': 'Sender data',
                'db_table': 'sender_data',
            },
        ),
        migrations.CreateModel(
            name='SenderOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_additions', models.DateTimeField(default=datetime.datetime(2018, 7, 11, 13, 24, 6, 948775), verbose_name='Date additions')),
                ('address', models.CharField(max_length=40, null=True, verbose_name='Address wallet for order')),
                ('contract', models.CharField(max_length=40, verbose_name='Smart contract address')),
                ('work_contract', models.CharField(max_length=40, null=True, verbose_name='Address work contract')),
                ('payment', models.BooleanField(default=False, verbose_name='Payment for services')),
                ('tokens', models.BooleanField(default=False, verbose_name='Ready for launch')),
                ('status', models.SmallIntegerField(default=-1, verbose_name='Status order')),
                ('cost', models.IntegerField(verbose_name='Service cost')),
                ('amount', models.IntegerField(verbose_name='Count all tokens')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='user.User', verbose_name='User')),
            ],
            options={
                'db_table': 'sender_order',
            },
        ),
        migrations.AddField(
            model_name='recipientdata',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_odrer', to='sender.SenderOrder', verbose_name='Order'),
        ),
    ]
