# Generated by Django 2.0.7 on 2018-07-11 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_auto_20180711_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderorder',
            name='amount',
            field=models.BigIntegerField(verbose_name='Count all tokens'),
        ),
        migrations.AlterField(
            model_name='senderorder',
            name='cost',
            field=models.BigIntegerField(verbose_name='Service cost'),
        ),
        migrations.AlterField(
            model_name='senderorder',
            name='date_additions',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 15, 34, 6, 349731), verbose_name='Date additions'),
        ),
    ]
