# Generated by Django 2.0.7 on 2018-07-11 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_auto_20180711_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderorder',
            name='amount',
            field=models.BigIntegerField(max_length=32, verbose_name='Count all tokens'),
        ),
        migrations.AlterField(
            model_name='senderorder',
            name='cost',
            field=models.BigIntegerField(max_length=32, verbose_name='Service cost'),
        ),
        migrations.AlterField(
            model_name='senderorder',
            name='date_additions',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 15, 37, 57, 590914), verbose_name='Date additions'),
        ),
    ]
