# Generated by Django 2.0.7 on 2018-07-11 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0006_auto_20180711_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderorder',
            name='date_additions',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 15, 53, 2, 518047), verbose_name='Date additions'),
        ),
    ]
