# Generated by Django 2.0.7 on 2018-07-11 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0007_auto_20180711_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderorder',
            name='amount',
            field=models.CharField(max_length=64, verbose_name='Count all tokens'),
        ),
        migrations.AlterField(
            model_name='senderorder',
            name='cost',
            field=models.CharField(max_length=64, verbose_name='Service cost'),
        ),
        migrations.AlterField(
            model_name='senderorder',
            name='date_additions',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 16, 7, 13, 932117), verbose_name='Date additions'),
        ),
    ]
