# Generated by Django 2.0.7 on 2018-07-11 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0008_auto_20180711_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientdata',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='senderorder',
            name='date_additions',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 17, 6, 23, 232771), verbose_name='Date additions'),
        ),
    ]
