# Generated by Django 2.0.7 on 2018-07-11 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Login name user (email)')),
                ('password', models.TextField(verbose_name='Password hash')),
                ('date_registration', models.DateTimeField(default=datetime.datetime(2018, 7, 11, 13, 24, 6, 946167), verbose_name='User registration date')),
                ('active', models.BooleanField(default=False, verbose_name='Activated account')),
                ('label', models.CharField(max_length=64, verbose_name='Name salt file')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'user',
            },
        ),
    ]
