# Generated by Django 2.0.7 on 2018-07-11 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180711_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 15, 37, 57, 589704), verbose_name='User registration date'),
        ),
    ]
