# Generated by Django 2.0.7 on 2018-07-11 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180711_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 15, 42, 0, 394187), verbose_name='User registration date'),
        ),
    ]
