# Generated by Django 2.0.7 on 2018-07-11 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180711_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 16, 7, 13, 930740), verbose_name='User registration date'),
        ),
    ]
