# Generated by Django 2.0.7 on 2018-07-11 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180711_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 17, 6, 23, 231350), verbose_name='User registration date'),
        ),
    ]
